name: ci
on:
  push:
    branches: [master]
  pull_request:

jobs:
  current-go:
    runs-on: ubuntu-latest
    container:
      image: cimg/go:1.15
    env:
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - name: Setup required permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: restore cache
        uses: actions/cache@v2
        env:
          cache-name: cache-go-mod
        with:
          path: /home/circleci/go/pkg/mod
          key: cimg-go-pkg-mod-{{ checksum "go.sum" }}
      - name: Precommit and Coverage Report
        run: |
          make ci
          mkdir $TEST_RESULTS/
          cp coverage.out $TEST_RESULTS/
          cp coverage.txt $TEST_RESULTS/
          cp coverage.html $TEST_RESULTS/
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true
      - name: store test output
        uses: actions/upload-artifact@v2
        with:
            name: opentelemetry-go-test-output
            path: /tmp/test-results
      - name: store test results
        uses: actions/upload-artifact@v2
        with:
            name: opentelemetry-go-test-output
            path: /tmp/test-results
  prior-go:
    runs-on: ubuntu-latest
    container:
      image: cimg/go:1.14
    env:
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - name: Setup required permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: restore cache
        uses: actions/cache@v2
        env:
          cache-name: cache-go-mod
        with:
          path: /home/circleci/go/pkg/mod
          key: cimg-go-pkg-mod-{{ checksum "go.sum" }}
      - name: Precommit and Coverage Report
        run: |
          make ci
          mkdir $TEST_RESULTS/
          cp coverage.out $TEST_RESULTS/
          cp coverage.txt $TEST_RESULTS/
          cp coverage.html $TEST_RESULTS/
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true
      - name: store test output
        uses: actions/upload-artifact@v2
        with:
            name: opentelemetry-go-test-output
            path: /tmp/test-results
      - name: store test results
        uses: actions/upload-artifact@v2
        with:
            name: opentelemetry-go-test-output
            path: /tmp/test-results