name: cd
on:
  schedule:
    - cron: '*/5 * * * *' # '59 23 * * *'
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # ensures we fetch all history for all branches and tags
      - name: Update Nightly Tag
        run: |
          git
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Verify Build # maybe we should move this to a release triggered worfklow
      #   run: ./verify_examples.sh
# test